CREATE DATABASE WebApi;

CREATE TABLE users (
  id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(200) NOT NULL,
  name VARCHAR(200) NOT NULL,
  lastname VARCHAR(200) NOT NULL,
  birthday DATE NOT NULL,
  password VARCHAR(200) NOT NULL
);